[tool.poetry]
name = "balena-custom-os"
version = "0.1.0"
description = "Exploit for poetry install"
authors = ["Exploiter"]

[tool.poetry.dependencies]
python = "^3.8"
pwn = { path = "./pwn", develop = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
